# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './monitor/page1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1360, 868)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 0, 1321, 851))
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(90, 640, 161, 71))
        self.pushButton.setStyleSheet("background-color: rgb(180, 180, 180);\n"
"font: 14pt \"华文彩云\";\n"
"color: rgb(0, 0, 0);\n"
"alternate-background-color: rgb(221, 255, 224);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 760, 161, 71))
        self.pushButton_2.setStyleSheet("background-color: rgb(180, 180, 180);\n"
"font: 14pt \"华文彩云\";\n"
"color: rgb(0, 0, 0);\n"
"alternate-background-color: rgb(221, 255, 224);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(220, 50, 501, 121))
        self.label_2.setStyleSheet("color: rgb(34, 0, 0);\n"
"font: 28pt \"Bernard MT Condensed\";\n"
"border-color: rgb(109, 99, 255);\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(830, 210, 281, 61))
        self.label_3.setStyleSheet("color: rgb(34, 0, 0);\n"
"font: 28pt \"Bernard MT Condensed\";\n"
"border-color: rgb(109, 99, 255);\n"
"\n"
"")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.goin) # type: ignore
        self.pushButton_2.clicked.connect(Dialog.goin2) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "车辆检测"))
        self.pushButton_2.setText(_translate("Dialog", "车型检测"))
        self.label_2.setText(_translate("Dialog", "\"Vehicle and Vehicle Type\""))
        self.label_3.setText(_translate("Dialog", "Detection Tool"))
